name: PHP quickscraper-sdk CI
on:
  push:
  pull_request:
  schedule:
    - cron: "* */5 * * *"

env:
  QS_ACCESS_TOKEN: ${{ secrets.QS_ACCESS_TOKEN }}
  DEBUG: "QS:*"

jobs:
  tests:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/phpunit@v8
        with:
          memory_limit: 256M

      - name: Execute tests
        run: vendor/bin/phpunit/phpunit --configuration 'phpunit.xml' --test-suffix 'Test.php,.phpt' -d memory_limit=256M