name: PHP quickscraper-sdk CI
on:
  push:
  pull_request:
  schedule:
    - cron: "* */5 * * *"

env:
  QS_ACCESS_TOKEN: ${{ secrets.QS_ACCESS_TOKEN }}
  DEBUG: "QS:*"

jobs:
  tests:
    name: PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: php-actions/phpunit@v8
        with:
          configuration: ~/phpunit.xml
          memory_limit: 256M